version: "3.8"

services:
  fastapi:
    build: .
    container_name: fastapi
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:mysecretpassword@db:5432/bot_user
    depends_on:
      db:
        condition: service_healthy  
    command: >
      sh -c "while ! nc -z db 5432; do
      echo 'Waiting for database...'; sleep 1; done;
      uvicorn app.main:app --host 0.0.0.0 --port 8080"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: bot_user
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"  # Порт Grafana
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana  # Для сохранения данных Grafana

volumes:
  grafana-data:
